# Generated by Django 4.2.7 on 2023-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='customer_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
