# Generated by Django 4.2.7 on 2023-11-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
