# Generated by Django 4.2.7 on 2023-11-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=100)),
                ('branch_id', models.IntegerField()),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipo_cliente')),
            ],
        ),
    ]
