# Generated by Django 4.2.7 on 2023-11-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_alter_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
