# Generated by Django 4.2.7 on 2023-11-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_customer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_account', models.TextField()),
            ],
            options={
                'db_table': 'tipo_cuenta',
                'managed': False,
            },
        ),
    ]
