# Generated by Django 4.2.7 on 2023-11-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(default='Aprobado', max_length=30),
            preserve_default=False,
        ),
    ]
